############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
# Frontend build
FROM nginx:alpine

LABEL maintainer="Elias De Hondt <elias.dehondt@outlook.com>"
LABEL version="1.0"
LABEL description="This is the frontend image for the app."

COPY ./index.html /usr/share/nginx/html/index.html

EXPOSE 80